
--CREACION DE BD INVENTARIO
CREATE DATABASE INVENTARIO
GO

--USO DE BD INVENTARIO
USE INVENTARIO
GO

--CREACION DE LA TABLA MOV_INVENTARIO
--DROP TABLE MOV_INVENTARIO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'MOV_INVENTARIO')
	CREATE TABLE dbo.MOV_INVENTARIO (
		COD_CIA VARCHAR(5) NOT NULL,
		COMPANIA_VENTA_3 VARCHAR(5) NOT NULL,
		ALMACEN_VENTA VARCHAR(10) NOT NULL,
		TIPO_MOVIMIENTO VARCHAR(2) NOT NULL,
		TIPO_DOCUMENTO VARCHAR(2) NOT NULL,
		NRO_DOCUMENTO VARCHAR(50) NOT NULL,
		COD_ITEM_2 VARCHAR(50) NOT NULL,
		PROVEEDOR VARCHAR(100) NULL,
		ALMACEN_DESTINO VARCHAR(50) NULL,
		CANTIDAD INT NULL,
		DOC_REF_1 VARCHAR(50) NULL,
		DOC_REF_2 VARCHAR(50) NULL,
		DOC_REF_3 VARCHAR(50) NULL,
		DOC_REF_4 VARCHAR(50) NULL,
		DOC_REF_5 VARCHAR(50) NULL,
		FECHA_TRANSACCION DATE NULL,
		CONSTRAINT PK_MOV_INVENTARIO PRIMARY KEY CLUSTERED (
		COD_CIA,
		COMPANIA_VENTA_3,
		ALMACEN_VENTA,
		TIPO_MOVIMIENTO,
		TIPO_DOCUMENTO,
		NRO_DOCUMENTO,
		COD_ITEM_2
		)
	);

--DATA DE PRUEBAS
INSERT INTO dbo.MOV_INVENTARIO (
    COD_CIA, COMPANIA_VENTA_3, ALMACEN_VENTA, TIPO_MOVIMIENTO, TIPO_DOCUMENTO,
    NRO_DOCUMENTO, COD_ITEM_2, PROVEEDOR, ALMACEN_DESTINO, CANTIDAD,
    DOC_REF_1, DOC_REF_2, DOC_REF_3, DOC_REF_4, DOC_REF_5, FECHA_TRANSACCION
)
VALUES
('001', '001', 'ALM01', '01', 'FA', 'DOC0001', 'ITEM001', 'Proveedor A', 'ALM02', 10, 'REF1A', NULL, NULL, NULL, NULL, '2025-06-01'),
('001', '001', 'ALM01', '02', 'FA', 'DOC0002', 'ITEM002', 'Proveedor B', 'ALM03', 15, 'REF2A', 'REF2B', NULL, NULL, NULL, '2025-06-02'),
('001', '001', 'ALM02', '01', 'NC', 'DOC0003', 'ITEM003', NULL, 'ALM01', 5, NULL, NULL, NULL, NULL, NULL, '2025-06-03'),
('002', '002', 'ALM01', '03', 'FA', 'DOC0004', 'ITEM004', 'Proveedor C', NULL, 20, NULL, NULL, NULL, NULL, NULL, '2025-06-04'),
('002', '002', 'ALM03', '01', 'FA', 'DOC0005', 'ITEM005', 'Proveedor D', 'ALM04', 8, NULL, NULL, NULL, NULL, NULL, '2025-06-05'),
('001', '001', 'ALM01', '02', 'NC', 'DOC0006', 'ITEM006', NULL, NULL, 12, NULL, NULL, NULL, NULL, NULL, '2025-06-06'),
('001', '001', 'ALM02', '01', 'FA', 'DOC0007', 'ITEM007', 'Proveedor E', 'ALM05', 30, 'REF7A', NULL, NULL, NULL, NULL, '2025-06-07'),
('003', '003', 'ALM04', '04', 'FA', 'DOC0008', 'ITEM008', NULL, NULL, 7, NULL, NULL, NULL, NULL, NULL, '2025-06-08'),
('002', '002', 'ALM03', '01', 'NC', 'DOC0009', 'ITEM009', 'Proveedor F', 'ALM01', 18, 'REF9A', 'REF9B', NULL, NULL, NULL, '2025-06-09'),
('003', '003', 'ALM05', '01', 'FA', 'DOC0010', 'ITEM010', 'Proveedor G', 'ALM02', 25, NULL, NULL, NULL, NULL, NULL, '2025-06-10');


--CREACION DE PROCEDIMIENTO ALMACENADO SP_CONSULTAR_MOVINVENTARIO
CREATE PROCEDURE SP_CONSULTAR_MOVINVENTARIO
	@FECHAINICIO DATE = NULL,
	@FECHAFIN DATE = NULL,
	@TIPO_MOVIMIENTO VARCHAR(2) = NULL,
	@NRO_DOCUMENTO VARCHAR(50) = NULL
AS
BEGIN
	IF @FECHAINICIO = '' SET @FECHAINICIO = NULL
	IF @FECHAFIN = '' SET @FECHAFIN = NULL
	IF @TIPO_MOVIMIENTO = '' SET @TIPO_MOVIMIENTO = NULL
	IF @NRO_DOCUMENTO = '' SET @NRO_DOCUMENTO = NULL

	SELECT 
		COD_CIA,
		COMPANIA_VENTA_3,
		ALMACEN_VENTA,
		TIPO_MOVIMIENTO,
		TIPO_DOCUMENTO,
		NRO_DOCUMENTO,
		COD_ITEM_2,
		PROVEEDOR,
		ALMACEN_DESTINO,
		CANTIDAD,
		DOC_REF_1,
		DOC_REF_2,
		DOC_REF_3,
		DOC_REF_4,
		DOC_REF_5,
		FECHA_TRANSACCION
	FROM dbo.MOV_INVENTARIO
	WHERE (@FECHAINICIO IS NULL OR FECHA_TRANSACCION >= @FECHAINICIO)
		AND (@FECHAFIN IS NULL OR FECHA_TRANSACCION <= @FECHAFIN)
		AND (@TIPO_MOVIMIENTO IS NULL OR TIPO_MOVIMIENTO = @TIPO_MOVIMIENTO)
		AND (@NRO_DOCUMENTO IS NULL OR NRO_DOCUMENTO = @NRO_DOCUMENTO);
END

--OBETNER DE PROCEDIMIENTO ALMACENADO SP_OBTENER_MOVINVENTARIO
CREATE PROCEDURE SP_OBTENER_MOVINVENTARIO
	@COD_CIA VARCHAR(5),
    @COMPANIA_VENTA_3 VARCHAR(5),
    @ALMACEN_VENTA VARCHAR(10),
    @TIPO_MOVIMIENTO VARCHAR(2),
    @TIPO_DOCUMENTO VARCHAR(2),
    @NRO_DOCUMENTO VARCHAR(50),
    @COD_ITEM_2 VARCHAR(50)
AS
BEGIN
	SELECT 
		COD_CIA,
		COMPANIA_VENTA_3,
		ALMACEN_VENTA,
		TIPO_MOVIMIENTO,
		TIPO_DOCUMENTO,
		NRO_DOCUMENTO,
		COD_ITEM_2,
		PROVEEDOR,
		ALMACEN_DESTINO,
		CANTIDAD,
		DOC_REF_1,
		DOC_REF_2,
		DOC_REF_3,
		DOC_REF_4,
		DOC_REF_5,
		FECHA_TRANSACCION
	FROM dbo.MOV_INVENTARIO
	WHERE
        COD_CIA = @COD_CIA AND
        COMPANIA_VENTA_3 = @COMPANIA_VENTA_3 AND
        ALMACEN_VENTA = @ALMACEN_VENTA AND
        TIPO_MOVIMIENTO = @TIPO_MOVIMIENTO AND
        TIPO_DOCUMENTO = @TIPO_DOCUMENTO AND
        NRO_DOCUMENTO = @NRO_DOCUMENTO AND
        COD_ITEM_2 = @COD_ITEM_2;
END

--CREACION DE PROCEDIMIENTO ALMACENADO SP_INSERTAR_MOVINVENTARIO
CREATE PROCEDURE SP_INSERTAR_MOVINVENTARIO
    @COD_CIA VARCHAR(5),
    @COMPANIA_VENTA_3 VARCHAR(5),
    @ALMACEN_VENTA VARCHAR(10),
    @TIPO_MOVIMIENTO VARCHAR(2),
    @TIPO_DOCUMENTO VARCHAR(2),
    @NRO_DOCUMENTO VARCHAR(50),
    @COD_ITEM_2 VARCHAR(50),
    @PROVEEDOR VARCHAR(100) = NULL,
    @ALMACEN_DESTINO VARCHAR(50) = NULL,
    @CANTIDAD INT = NULL,
    @DOC_REF_1 VARCHAR(50) = NULL,
    @DOC_REF_2 VARCHAR(50) = NULL,
    @DOC_REF_3 VARCHAR(50) = NULL,
    @DOC_REF_4 VARCHAR(50) = NULL,
    @DOC_REF_5 VARCHAR(50) = NULL,
    @FECHA_TRANSACCION DATE = NULL
AS
BEGIN
    INSERT INTO dbo.MOV_INVENTARIO (
        COD_CIA, 
		COMPANIA_VENTA_3, 
		ALMACEN_VENTA, 
		TIPO_MOVIMIENTO, 
		TIPO_DOCUMENTO,
        NRO_DOCUMENTO, 
		COD_ITEM_2, 
		PROVEEDOR, 
		ALMACEN_DESTINO, 
		CANTIDAD,
        DOC_REF_1, 
		DOC_REF_2, 
		DOC_REF_3, 
		DOC_REF_4, 
		DOC_REF_5, 
		FECHA_TRANSACCION
    )
    VALUES (
        @COD_CIA, 
		@COMPANIA_VENTA_3, 
		@ALMACEN_VENTA, 
		@TIPO_MOVIMIENTO, 
		@TIPO_DOCUMENTO,
        @NRO_DOCUMENTO, 
		@COD_ITEM_2, 
		@PROVEEDOR, 
		@ALMACEN_DESTINO, 
		@CANTIDAD,
        @DOC_REF_1, 
		@DOC_REF_2, 
		@DOC_REF_3, 
		@DOC_REF_4, 
		@DOC_REF_5, 
		@FECHA_TRANSACCION
    );
END;


--CREACION DE PROCEDIMIENTO ALMACENADO SP_ACTUALIZAR_MOVINVENTARIO
CREATE PROCEDURE SP_ACTUALIZAR_MOVINVENTARIO
    @COD_CIA VARCHAR(5),
    @COMPANIA_VENTA_3 VARCHAR(5),
    @ALMACEN_VENTA VARCHAR(10),
    @TIPO_MOVIMIENTO VARCHAR(2),
    @TIPO_DOCUMENTO VARCHAR(2),
    @NRO_DOCUMENTO VARCHAR(50),
    @COD_ITEM_2 VARCHAR(50),
    @PROVEEDOR VARCHAR(100) = NULL,
    @ALMACEN_DESTINO VARCHAR(50) = NULL,
    @CANTIDAD INT = NULL,
    @DOC_REF_1 VARCHAR(50) = NULL,
    @DOC_REF_2 VARCHAR(50) = NULL,
    @DOC_REF_3 VARCHAR(50) = NULL,
    @DOC_REF_4 VARCHAR(50) = NULL,
    @DOC_REF_5 VARCHAR(50) = NULL,
    @FECHA_TRANSACCION DATE = NULL
AS
BEGIN
    UPDATE dbo.MOV_INVENTARIO
    SET
        PROVEEDOR = @PROVEEDOR,
        ALMACEN_DESTINO = @ALMACEN_DESTINO,
        CANTIDAD = @CANTIDAD,
        DOC_REF_1 = @DOC_REF_1,
        DOC_REF_2 = @DOC_REF_2,
        DOC_REF_3 = @DOC_REF_3,
        DOC_REF_4 = @DOC_REF_4,
        DOC_REF_5 = @DOC_REF_5,
        FECHA_TRANSACCION = @FECHA_TRANSACCION
    WHERE
        COD_CIA = @COD_CIA AND
        COMPANIA_VENTA_3 = @COMPANIA_VENTA_3 AND
        ALMACEN_VENTA = @ALMACEN_VENTA AND
        TIPO_MOVIMIENTO = @TIPO_MOVIMIENTO AND
        TIPO_DOCUMENTO = @TIPO_DOCUMENTO AND
        NRO_DOCUMENTO = @NRO_DOCUMENTO AND
        COD_ITEM_2 = @COD_ITEM_2;
END;


--CREACION DE PROCEDIMIENTO ALMACENADO SP_ELIMINAR_MOVINVENTARIO
CREATE PROCEDURE SP_ELIMINAR_MOVINVENTARIO
    @COD_CIA VARCHAR(5),
    @COMPANIA_VENTA_3 VARCHAR(5),
    @ALMACEN_VENTA VARCHAR(10),
    @TIPO_MOVIMIENTO VARCHAR(2),
    @TIPO_DOCUMENTO VARCHAR(2),
    @NRO_DOCUMENTO VARCHAR(50),
    @COD_ITEM_2 VARCHAR(50)
AS
BEGIN
    DELETE FROM dbo.MOV_INVENTARIO
    WHERE
        COD_CIA = @COD_CIA AND
        COMPANIA_VENTA_3 = @COMPANIA_VENTA_3 AND
        ALMACEN_VENTA = @ALMACEN_VENTA AND
        TIPO_MOVIMIENTO = @TIPO_MOVIMIENTO AND
        TIPO_DOCUMENTO = @TIPO_DOCUMENTO AND
        NRO_DOCUMENTO = @NRO_DOCUMENTO AND
        COD_ITEM_2 = @COD_ITEM_2;
END;
